/* ============================================================
   KONFIGURASI AUDIO — BGM per suasana cerita + SFX
   Taruh file musik kamu di:
     assets/music/bgm/<nama>.mp3   (BGM, disesuaikan mood tiap scene)
     assets/music/sfx/<nama>.mp3   (SFX, generik — tidak terikat scene)
   Kalau nama file kamu beda, tinggal ganti path di bawah ini saja,
   tidak perlu ubah kode lain.
   ============================================================ */
const audioConfig = {
    BGM: {
        // Menu & transisi umum
        lobby:               'assets/music/bgm/lobby.mp3',
        daily_common:        'assets/music/bgm/daily_common.mp3',   // hari-hari biasa, koridor, netral
        comedy:              'assets/music/bgm/comedy.mp3',          // godaan Bima, momen ringan/lucu

        // Nuansa per "dunia" heroine
        council_focus:       'assets/music/bgm/council_focus.mp3',   // OSIS, Alexandra — disiplin & serius
        art_whimsy:          'assets/music/bgm/art_whimsy.mp3',      // Ruang Seni, Kirana — ceria & bebas
        mystery:             'assets/music/bgm/mystery.mp3',         // Mira, loteng arsip — tenang & misterius

        // Nuansa emosional lintas rute
        tender:              'assets/music/bgm/tender.mp3',          // momen hangat/lembut membangun kedekatan
        tension:              'assets/music/bgm/tension.mp3',         // konflik, ujian kepercayaan, krisis
        melancholy:           'assets/music/bgm/melancholy.mp3',      // sedih, ragu, kehilangan
        night_calm:            'assets/music/bgm/night_calm.mp3',      // adegan malam yang tenang (opsional dipakai manual)
        festival:              'assets/music/bgm/festival.mp3',        // Aula Festival, perayaan, upbeat

        // Ending
        ending_good:           'assets/music/bgm/ending_good.mp3',
        ending_bittersweet:    'assets/music/bgm/ending_bittersweet.mp3',
        ending_bad:             'assets/music/bgm/ending_bad.mp3',
        true_ending:            'assets/music/bgm/true_ending.mp3',
    },
    SFX: {
        click:    'assets/music/sfx/click.mp3',     // klik tombol/lanjut dialog (default)
        confirm:  'assets/music/sfx/confirm.mp3',   // konfirmasi pilihan penting
        save:     'assets/music/sfx/save.mp3',      // berhasil menyimpan
        unlock:   'assets/music/sfx/unlock.mp3',    // quote/karakter baru terbuka
        error:    'assets/music/sfx/error.mp3',     // aksi tidak valid / bad end
    }
};

const assets = {
    BACKGROUNDS: {
        sekolahUmum: {
            koridor:     'assets/background/koridor.png',
            kelas:       'assets/background/ruang_kelas.png',
            ruangGuruBK: 'assets/background/ruang_bk.png',
            taman:       'assets/background/taman.png',
            perpustakaan:'assets/background/perpustakaan.png',
            kantin:       'assets/background/kantin.png',
            lapanganBasket: 'assets/background/lapangan_basket.png',
        },
        osis: {
            sekretariat: 'assets/background/sekretariat_osis.png',
        },
        seni: {
            ruangSeni:   'assets/background/ruang_seni.png',
            sanggarLuar: 'assets/background/sanggar_luar.png',
        },
        luarSekolah: {
            pasarMalam:  'assets/background/pasar_malam.png',
            warkopSanggar: 'assets/background/warkop_sanggar.png',
        },
        spesial: {
            atapMalam:    'assets/background/atap_malam.png',
            aulaFestival: 'assets/background/aula_festival.png',
        },
        rahasia: {
            lotengArsip:  'assets/background/loteng_arsip.png',
            halteBus:     'assets/background/halte_bus.png',
        }
    },
    CHARACTER_PATHS: {
        alexandra: 'alexandra_wijaya',
        kirana:    'kirana_maheswari',
        mc:        'mc_protagonis',
        bima:      'bima_satrio',
        rangga:    'rangga_aditya',
        buSari:    'bu_sari',
        pakHendra: 'pak_hendra',
        farah:     'farah_novita',
        dewi:      'dewi',
        bangYusuf: 'bang_yusuf',
        mira:      'mira_anindya',
        alvin:     'alvin_pradana'
    }
};

const allQuotes = {
    quote_alexandra: "Kamu nggak bikin aku harus jadi 'Ketua OSIS' terus. Cukup jadi Alexandra aja. — Alexandra",
    quote_bad: "Aku cuma takut kalau aku jujur, aku bakal kelihatan lemah. — Alexandra",
    quote_kirana: "Ini karya paling berarti yang pernah aku buat. Bukan karena hasilnya, tapi karena siapa yang bikin bareng aku. — Kirana",
    quote_normal: "Nggak masalah, yang penting kamu nggak lari dari pertanyaannya. — Pak Hendra",
    quote_mira: "Ini pertama kalinya aku milih buat tinggal, bukan cuma nurutin ke mana pun aku dibawa pergi. Dan aku milih di sini. Sama kamu. — Mira",
    quote_epilog: "Bukan kisah cinta segitiga dengan satu pemenang, tapi tiga orang yang saling menemukan versi terbaik diri mereka. — Narator",
};

const locales = {
    en: {
        langName: "English",
        gameTitle: "My Favorite Corridor",
        gameSub: "A Romantic Visual Novel",
        btnContinue: "▶ CONTINUE",
        btnNewGame: "▶ NEW GAME",
        btnProfiles: "📖 CHARACTER PROFILES",
        btnGallery: "📖 QUOTE GALLERY",
        btnSettings: "⚙️ SETTINGS",
        inputTitle: "WHO ARE YOU?",
        inputSub: "Enter the protagonist's nickname",
        inputPlaceholder: "Example: Adi",
        inputBtnStart: "Start the Story",
        inputBtnCancel: "Cancel",
        pauseTitle: "⏸️ Pause",
        pauseSave: "💾 Save Game",
        pauseLoad: "📂 Load Game",
        pauseSettings: "⚙️ Settings",
        pauseQuit: "🚪 Quit Game",
        pauseBack: "Back",
        settingsTitle: "⚙️ Settings",
        settingsBGM: "🎵 BGM Volume",
        settingsSFX: "🔊 SFX Volume",
        settingsRes: "🖥️ Resolution",
        settingsLang: "🌐 Language",
        settingsBack: "Back",
        btnHowToPlay: "🕹️ How to Play",
        howToPlayTitle: "🕹️ How to Play",
        howToPlayDesc1: "In the Main Lobby: Use the <b>LEFT</b> and <b>RIGHT</b> Arrow keys to select menus. Press <b>SPACE</b> or <b>ENTER</b> to confirm.",
        howToPlayDesc2: "In the Game (when multiple choices appear): Use the <b>UP</b> and <b>DOWN</b> Arrow keys to select. Press <b>SPACE</b> or <b>ENTER</b> to confirm.",
        howToPlayDesc3: "During a dialogue with only one 'Continue' option: Press <b>SPACE</b> to instantly advance the text.",
        howToPlayClose: "Close",
        saveLoadTitleSave: "💾 Save Game",
        saveLoadTitleLoad: "📂 Load Game",
        saveLoadSubSave: "Select a slot to save your progress",
        saveLoadSubLoad: "Select a slot to load from",
        saveLoadBack: "Back",
        confirmYes: "Yes, Proceed",
        confirmNo: "Cancel",
        confirmQuitTitle: "🚪 Quit?",
        confirmQuitMsg: "Are you sure you want to quit? Unsaved progress will be lost.",
        confirmOverwriteTitle: "Overwrite Slot?",
        confirmOverwriteMsg: "Slot {n} is already filled ({date}). Overwrite with current progress?",
        confirmLoadTitle: "Load this Slot?",
        confirmLoadMsg: "Current unsaved progress will be lost. Continue loading Slot {n}?",
        confirmDeleteTitle: "Delete Slot?",
        confirmDeleteMsg: "Slot {n} will be permanently deleted and cannot be restored.",
        toastUnlock: "Something Unlocked!",
        toastUnlockMsg: "Check the menu to see it.",
        toastSave: "✅ Saved!",
        toastSaveMsg: "Progress successfully saved to Slot {n}.",
        profile_mc: "MC (Adi Pratama)",
        profile_alexandra: "Alexandra Wijaya",
        profile_kirana: "Kirana Maheswari",
        profile_mira: "Mira Anindya",
        profile_rangga: "Rangga Aditya",
        profile_farah: "Farah Novita",
        profile_bima: "Bima Satrio",
        profile_pakHendra: "Mr. Hendra",
        profile_buSari: "Mrs. Sari",
        profile_alvin: "Alvin Pradana",
        profile_dewi: "Dewi Anggraini",
        profile_bangYusuf: "Bang Yusuf",
        role_mc: "Protagonist",
        role_alexandra: "OSIS President",
        role_kirana: "School Art Genius",
        role_mira: "Transfer Student",
        role_rangga: "OSIS Vice President",
        role_farah: "OSIS Secretary",
        role_bima: "MC's Best Friend",
        role_pakHendra: "Homeroom Teacher (Math)",
        role_buSari: "Art Teacher",
        role_alvin: "Childhood Friend",
        role_dewi: "MC's Classmate",
        role_bangYusuf: "Art Studio Leader",
        desc_mc: "An ordinary 2nd-year high school student. Average grades, likes reading comics and napping in class. Kind-hearted, a bit awkward, but always tries to be honest with himself.",
        desc_alexandra: "Firm, disciplined, perfectionist. Behind her stern mask, she hides anxiety and loneliness. Afraid of disappointing others, and rarely lets anyone get close.",
        desc_kirana: "Cheerful, creative, and free-spirited. National painting competition champion. But secretly, she's afraid that if her talent ever fades, people will stop liking her.",
        desc_mira: "Quiet, guarded, and highly intelligent. Has changed schools four times in three years. Loves writing short stories in the library's archive attic, and has learned not to get too close to anyone so it won't hurt as much when she has to leave again.",
        desc_rangga: "Responsible and protective, especially of Alexandra. Deeply suspicious of MC at first, but eventually gives his blessing. Secretly has feelings for Alexandra.",
        desc_farah: "Warm and empathetic. Alexandra's best friend since middle school, often acting as the 'translator' for Alexandra's hard-to-express feelings. Always carries a small notebook.",
        desc_bima: "Humorous, chatty, and the school's go-to source for gossip. Annoying at times, but he's the most loyal friend, always ready to listen when MC needs to talk.",
        desc_pakHendra: "Strict about academics, but deeply caring. 28 years of teaching experience means he's hard to fool, and his advice is always wise.",
        desc_buSari: "Calm and patient. Kirana's mentor. She deliberately 'borrows' MC to help Kirana, so the two of them can get to know each other better.",
        desc_alvin: "Mira's friend since elementary school. Has liked her for a long time but is too afraid to say it. Kind-hearted, but can become a serious rival.",
        desc_dewi: "Sweet and shy, secretly has a crush on MC at the start of the story. Has the emotional maturity to accept reality without resentment, and becomes one of Mira's first friends at her new school.",
        desc_bangYusuf: "A 3rd-year senior, leader of an art studio outside school. Calm and mature, he treats Kirana like a little sister. Loyal without ever expecting anything in return.",
        quote_alexandra: "You don't make me feel like I always have to be the 'Council President'. I can just be Alexandra. — Alexandra",
        quote_bad: "I was just afraid that if I were honest, I'd look weak. — Alexandra",
        quote_kirana: "This is the most meaningful piece I've ever made. Not because of how it turned out, but because of who made it with me. — Kirana",
        quote_normal: "It's fine. What matters is that you didn't run from the question. — Mr. Hendra",
        quote_mira: "This is the first time I've ever chosen to stay, instead of just going along with wherever I'm taken. And I choose here. With you. — Mira",
        quote_epilog: "Not a love triangle with one winner, but three people who helped each other become the best version of themselves. — Narrator",
        lockText: "🔒 Locked",
        lockRouteA: "🔒 Complete Alexandra's Route",
        lockRouteB: "🔒 Complete Kirana's Route",
        lockRouteM: "🔒 Complete Mira's Route",
        lockSecret: "🔒 Complete All Heroines' Routes",
    },
    id: {
        langName: "Indonesia",
        gameTitle: "My Favorite Corridor",
        gameSub: "Romansa Sekolah Visual Novel",
        btnContinue: "▶ LANJUTKAN",
        btnNewGame: "▶ MULAI BARU",
        btnProfiles: "📖 PROFIL KARAKTER",
        btnGallery: "📖 KOLEKSI QUOTES",
        btnSettings: "⚙️ PENGATURAN",
        inputTitle: "SIAPA NAMA KAMU?",
        inputSub: "Masukkan nama panggilan karakter utama",
        inputPlaceholder: "Contoh: Adi",
        inputBtnStart: "Mulai Masuk Cerita",
        inputBtnCancel: "Batal",
        pauseTitle: "⏸️ Jeda",
        pauseSave: "💾 Simpan",
        pauseLoad: "📂 Lanjutkan (Muat Slot)",
        pauseSettings: "⚙️ Pengaturan",
        pauseQuit: "🚪 Keluar Game",
        pauseBack: "Kembali",
        settingsTitle: "⚙️ Pengaturan",
        settingsBGM: "🎵 Musik Latar (BGM)",
        settingsSFX: "🔊 Efek Suara (SFX)",
        settingsRes: "🖥️ Resolusi Layar",
        settingsLang: "🌐 Bahasa",
        settingsBack: "Kembali",
        btnHowToPlay: "🕹️ Cara Bermain",
        howToPlayTitle: "🕹️ Cara Bermain",
        howToPlayDesc1: "Di Lobby Utama: Gunakan tombol Panah <b>KIRI</b> dan <b>KANAN</b> untuk memilih menu. Tekan <b>SPASI</b> atau <b>ENTER</b> untuk konfirmasi.",
        howToPlayDesc2: "Di Dalam Game (saat banyak pilihan muncul): Gunakan tombol Panah <b>ATAS</b> dan <b>BAWAH</b> untuk memilih. Tekan <b>SPASI</b> atau <b>ENTER</b> untuk konfirmasi.",
        howToPlayDesc3: "Saat dialog hanya memiliki opsi 'Lanjut...': Tekan <b>SPASI</b> untuk langsung melanjutkan teks.",
        howToPlayClose: "Tutup",
        saveLoadTitleSave: "💾 Simpan Permainan",
        saveLoadTitleLoad: "📂 Muat Permainan",
        saveLoadSubSave: "Pilih slot untuk menyimpan progress kamu",
        saveLoadSubLoad: "Pilih slot yang ingin dimuat",
        saveLoadBack: "Kembali",
        confirmYes: "Ya, Lanjutkan",
        confirmNo: "Batal",
        confirmQuitTitle: "🚪 Keluar?",
        confirmQuitMsg: "Yakin ingin keluar game? Progress yang belum disimpan akan hilang.",
        confirmOverwriteTitle: "Timpa Slot?",
        confirmOverwriteMsg: "Slot {n} sudah terisi ({date}). Timpa dengan progress saat ini?",
        confirmLoadTitle: "Muat Slot Ini?",
        confirmLoadMsg: "Progress yang belum disimpan saat ini akan hilang. Lanjutkan memuat Slot {n}?",
        confirmDeleteTitle: "Hapus Slot?",
        confirmDeleteMsg: "Slot {n} akan dihapus permanen dan tidak bisa dikembalikan.",
        toastUnlock: "Sesuatu Terbuka!",
        toastUnlockMsg: "Cek menu untuk melihatnya.",
        toastSave: "✅ Tersimpan!",
        toastSaveMsg: "Progress berhasil disimpan di Slot {n}.",
        profile_mc: "MC (Adi Pratama)",
        profile_alexandra: "Alexandra Wijaya",
        profile_kirana: "Kirana Maheswari",
        profile_mira: "Mira Anindya",
        profile_rangga: "Rangga Aditya",
        profile_farah: "Farah Novita",
        profile_bima: "Bima Satrio",
        profile_pakHendra: "Pak Hendra",
        profile_buSari: "Bu Sari",
        profile_alvin: "Alvin Pradana",
        profile_dewi: "Dewi Anggraini",
        profile_bangYusuf: "Bang Yusuf",
        role_mc: "Protagonis",
        role_alexandra: "Ketua OSIS",
        role_kirana: "Jenius Seni Sekolah",
        role_mira: "Murid Pindahan",
        role_rangga: "Wakil Ketua OSIS",
        role_farah: "Sekretaris OSIS",
        role_bima: "Sahabat MC",
        role_pakHendra: "Wali Kelas (Guru Matematika)",
        role_buSari: "Guru Seni",
        role_alvin: "Sahabat Masa Kecil",
        role_dewi: "Teman Sekelas MC",
        role_bangYusuf: "Ketua Sanggar Lukis",
        desc_mc: "Murid kelas 2 SMA biasa. Nilai pas-pasan, hobi baca komik dan tidur di kelas. Baik hati, agak canggung, tapi selalu berusaha jujur pada dirinya sendiri.",
        desc_alexandra: "Tegas, disiplin, perfeksionis. Di balik topeng ketegasannya, dia menyimpan kecemasan dan kesepian. Takut mengecewakan orang lain dan jarang membiarkan siapa pun dekat.",
        desc_kirana: "Ceria, kreatif, dan bebas. Juara lomba lukis nasional. Namun diam-diam ia takut jika suatu hari bakatnya hilang, orang-orang akan berhenti menyukainya.",
        desc_mira: "Pendiam, waspada, dan sangat cerdas. Sudah pindah sekolah empat kali dalam tiga tahun. Suka menulis cerpen di loteng arsip perpustakaan, dan belajar untuk tidak terlalu dekat dengan siapa pun agar tidak sakit hati saat harus pergi lagi.",
        desc_rangga: "Bertanggung jawab dan protektif, terutama pada Alexandra. Awalnya sangat curiga pada MC, tapi akhirnya memberikan restunya. Diam-diam menyukai Alexandra.",
        desc_farah: "Ramah dan empatik. Sahabat Alexandra sejak SMP, sering menjadi \"penerjemah\" perasaan Alexandra yang sulit diungkapkan. Selalu membawa buku catatan kecil.",
        desc_bima: "Humoris, cerewet, dan sumber gosip sekolah. Meski kadang nyebelin, dia adalah sahabat paling setia yang selalu siap jadi tempat curhat MC.",
        desc_pakHendra: "Tegas soal akademik, tetapi sangat perhatian. Pengalaman mengajar 28 tahun membuatnya tidak mudah dibohongi, dan nasihatnya selalu bijak.",
        desc_buSari: "Tenang dan sabar. Mentor Kirana. Dia sengaja \"meminjam\" MC untuk membantu Kirana agar mereka berdua bisa saling mengenal lebih dalam.",
        desc_alvin: "Sahabat Mira sejak SD. Sudah lama menyukainya tapi takut mengungkapkan. Baik hati, tapi bisa menjadi rival yang serius.",
        desc_dewi: "Manis dan pemalu, diam-diam menyukai MC di awal cerita. Punya kedewasaan emosional untuk menerima kenyataan tanpa dendam, dan jadi salah satu sahabat pertama Mira di sekolah baru.",
        desc_bangYusuf: "Senior kelas 3, ketua sanggar lukis di luar sekolah. Kalem dan dewasa, menganggap Kirana seperti adik sendiri. Loyal tanpa pernah menuntut balasan.",
        quote_alexandra: "Kamu nggak bikin aku harus jadi 'Ketua OSIS' terus. Cukup jadi Alexandra aja. — Alexandra",
        quote_bad: "Aku cuma takut kalau aku jujur, aku bakal kelihatan lemah. — Alexandra",
        quote_kirana: "Ini karya paling berarti yang pernah aku buat. Bukan karena hasilnya, tapi karena siapa yang bikin bareng aku. — Kirana",
        quote_normal: "Nggak masalah, yang penting kamu nggak lari dari pertanyaannya. — Pak Hendra",
        quote_mira: "Ini pertama kalinya aku milih buat tinggal, bukan cuma nurutin ke mana pun aku dibawa pergi. Dan aku milih di sini. Sama kamu. — Mira",
        quote_epilog: "Bukan kisah cinta segitiga dengan satu pemenang, tapi tiga orang yang saling menemukan versi terbaik diri mereka. — Narator",
        lockText: "🔒 Terkunci",
        lockRouteA: "🔒 Selesaikan Rute Alexandra",
        lockRouteB: "🔒 Selesaikan Rute Kirana",
        lockRouteM: "🔒 Selesaikan Rute Mira",
        lockSecret: "🔒 Selesaikan Semua Rute Heroine",
    }
};

const characterProfiles = {
    mc: { id: 'mc', name: 'MC (Adi Pratama)', role: 'Protagonis', desc: 'Murid kelas 2 SMA biasa. Nilai pas-pasan, hobi baca komik dan tidur di kelas. Baik hati, agak canggung, tapi selalu berusaha jujur pada dirinya sendiri.', unlockKey: null },
    alexandra: { id: 'alexandra', name: 'Alexandra Wijaya', role: 'Ketua OSIS', desc: 'Tegas, disiplin, perfeksionis. Di balik topeng ketegasannya, dia menyimpan kecemasan dan kesepian. Takut mengecewakan orang lain dan jarang membiarkan siapa pun dekat.', unlockKey: 'routeA' },
    kirana: { id: 'kirana', name: 'Kirana Maheswari', role: 'Jenius Seni Sekolah', desc: 'Ceria, kreatif, dan bebas. Juara lomba lukis nasional. Namun diam-diam ia takut jika suatu hari bakatnya hilang, orang-orang akan berhenti menyukainya.', unlockKey: 'routeB' },
    mira: { id: 'mira', name: 'Mira Anindya', role: 'Murid Pindahan', desc: 'Pendiam, waspada, dan sangat cerdas. Sudah pindah sekolah empat kali dalam tiga tahun. Suka menulis cerpen di loteng arsip perpustakaan, dan belajar untuk tidak terlalu dekat dengan siapa pun agar tidak sakit hati saat harus pergi lagi.', unlockKey: 'routeM' },
    rangga: { id: 'rangga', name: 'Rangga Aditya', role: 'Wakil Ketua OSIS', desc: 'Bertanggung jawab dan protektif, terutama pada Alexandra. Awalnya sangat curiga pada MC, tapi akhirnya memberikan restunya. Diam-diam menyukai Alexandra.', unlockKey: 'secretRoute' },
    farah: { id: 'farah', name: 'Farah Novita', role: 'Sekretaris OSIS', desc: 'Ramah dan empatik. Sahabat Alexandra sejak SMP, sering menjadi "penerjemah" perasaan Alexandra yang sulit diungkapkan. Selalu membawa buku catatan kecil.', unlockKey: 'secretRoute' },
    bima: { id: 'bima', name: 'Bima Satrio', role: 'Sahabat MC', desc: 'Humoris, cerewet, dan sumber gosip sekolah. Meski kadang nyebelin, dia adalah sahabat paling setia yang selalu siap jadi tempat curhat MC.', unlockKey: null },
    pakHendra: { id: 'pakHendra', name: 'Pak Hendra', role: 'Wali Kelas (Guru Matematika)', desc: 'Tegas soal akademik, tetapi sangat perhatian. Pengalaman mengajar 28 tahun membuatnya tidak mudah dibohongi, dan nasihatnya selalu bijak.', unlockKey: null },
    buSari: { id: 'buSari', name: 'Bu Sari', role: 'Guru Seni', desc: 'Tenang dan sabar. Mentor Kirana. Dia sengaja "meminjam" MC untuk membantu Kirana agar mereka berdua bisa saling mengenal lebih dalam.', unlockKey: 'secretRoute' },
    alvin: { id: 'alvin', name: 'Alvin Pradana', role: 'Sahabat Masa Kecil', desc: 'Sahabat Mira sejak SD. Sudah lama menyukainya tapi takut mengungkapkan. Baik hati, tapi bisa menjadi rival yang serius.', unlockKey: null },
    dewi: { id: 'dewi', name: 'Dewi Anggraini', role: 'Teman Sekelas MC', desc: 'Manis dan pemalu, diam-diam menyukai MC di awal cerita. Punya kedewasaan emosional untuk menerima kenyataan tanpa dendam, dan jadi salah satu sahabat pertama Mira di sekolah baru.', unlockKey: null },
    bangYusuf: { id: 'bangYusuf', name: 'Bang Yusuf', role: 'Ketua Sanggar Lukis', desc: 'Senior kelas 3, ketua sanggar lukis di luar sekolah. Kalem dan dewasa, menganggap Kirana seperti adik sendiri. Loyal tanpa pernah menuntut balasan.', unlockKey: 'routeB' }
};