const assets = {
    BACKGROUNDS: {
        sekolahUmum: {
            koridor:     'assets/background/koridor.png',
            kelas:       'assets/background/ruang_kelas.png',
            ruangGuruBK: 'assets/background/ruang_bk.png',
            taman:       'assets/background/taman.png',
            perpustakaan:'assets/background/perpustakaan.png',
        },
        osis: {
            sekretariat: 'assets/background/sekretariat_osis.png',
        },
        seni: {
            ruangSeni:   'assets/background/ruang_seni.png',
            sanggarLuar: 'assets/background/sanggar_luar.png',
        },
        luarSekolah: {
            pasarMalam:  'assets/background/pasar_malam.png',
        },
        spesial: {
            atapMalam:    'assets/background/atap_malam.png',
            aulaFestival: 'assets/background/aula_festival.png',
        },
        rahasia: {
            lotengArsip:  'assets/background/loteng_arsip.png',
            halteBus:     'assets/background/halte_bus.png',
        }
    },
    CHARACTER_PATHS: {
        alexandra: 'alexandra_wijaya',
        kirana:    'kirana_maheswari',
        mc:        'mc_protagonis',
        bima:      'bima_satrio',
        rangga:    'rangga_aditya',
        buSari:    'bu_sari',
        pakHendra: 'pak_hendra',
        farah:     'farah_novita',
        dewi:      'dewi',
        bangYusuf: 'bang_yusuf',
        mira:      'mira_anindya',
        alvin:     'alvin_pradana'
    }
};

const allQuotes = {
    quote_a1: "Kamu nggak bikin aku harus jadi 'Ketua OSIS' terus. Cukup jadi Alexandra aja. — Alexandra",
    quote_b1: "Ini karya paling berarti yang pernah aku buat. Bukan karena hasilnya, tapi karena siapa yang bikin bareng aku. — Kirana",
    quote_m1: "Ini pertama kalinya aku milih buat tinggal, bukan cuma nurutin ke mana pun aku dibawa pergi. Dan aku milih di sini. Sama kamu. — Mira",
    quote_c: "Nilai ulanganmu minggu ini naik. Saya masih belum tahu jawabannya, Pak. Nggak masalah, yang penting kamu nggak lari dari pertanyaannya. — Pak Hendra",
    quote_r1: "Bukan kisah cinta segitiga dengan satu pemenang, tapi tiga orang yang saling menemukan versi terbaik diri mereka. — Narator",
    quote_r2: "Terima kasih sudah memilihku. / Senang banget kamu memilihku! — Alexandra & Kirana",
    quote_a2: "Aku cuma takut kalau aku jujur, aku bakal kelihatan lemah. — Alexandra",
    quote_b2: "Ternyata seru juga jadi orang biasa. Makasih udah nunjukin ini. — Kirana",
    quote_m3: "Makasih udah jadi tempat yang nggak pernah bikin aku ngerasa cuma 'numpang lewat'. Aku bakal selalu inget loteng itu. Dan kamu. — Mira",
};

const locales = {
    en: {
        langName: "English",
        gameTitle: "Crossroads of Hearts",
        gameSub: "A School Romance Visual Novel",
        btnContinue: "▶ CONTINUE",
        btnNewGame: "▶ NEW GAME",
        btnProfiles: "📖 CHARACTER PROFILES",
        btnGallery: "📖 QUOTE GALLERY",
        btnSettings: "⚙️ SETTINGS",
        inputTitle: "WHO ARE YOU?",
        inputSub: "Enter the protagonist's nickname",
        inputPlaceholder: "Example: Adi",
        inputBtnStart: "Start the Story",
        inputBtnCancel: "Cancel",
        pauseTitle: "⏸️ Pause",
        pauseSave: "💾 Save Game",
        pauseLoad: "📂 Load Game",
        pauseSettings: "⚙️ Settings",
        pauseQuit: "🚪 Quit Game",
        pauseBack: "Back",
        settingsTitle: "⚙️ Settings",
        settingsBGM: "🎵 BGM Volume",
        settingsSFX: "🔊 SFX Volume",
        settingsRes: "🖥️ Resolution",
        settingsLang: "🌐 Language",
        settingsBack: "Back",
        saveLoadTitleSave: "💾 Save Game",
        saveLoadTitleLoad: "📂 Load Game",
        saveLoadSubSave: "Select a slot to save your progress",
        saveLoadSubLoad: "Select a slot to load from",
        saveLoadBack: "Back",
        confirmYes: "Yes, Proceed",
        confirmNo: "Cancel",
        confirmQuitTitle: "🚪 Quit?",
        confirmQuitMsg: "Are you sure you want to quit? Unsaved progress will be lost.",
        confirmOverwriteTitle: "Overwrite Slot?",
        confirmOverwriteMsg: "Slot {n} is already filled ({date}). Overwrite with current progress?",
        confirmLoadTitle: "Load this Slot?",
        confirmLoadMsg: "Current unsaved progress will be lost. Continue loading Slot {n}?",
        confirmDeleteTitle: "Delete Slot?",
        confirmDeleteMsg: "Slot {n} will be permanently deleted and cannot be restored.",
        toastUnlock: "Something Unlocked!",
        toastUnlockMsg: "Check the menu to see it.",
        toastSave: "✅ Saved!",
        toastSaveMsg: "Progress successfully saved to Slot {n}.",
        profile_mc: "MC (Adi Pratama)",
        profile_alexandra: "Alexandra Wijaya",
        profile_kirana: "Kirana Maheswari",
        profile_mira: "Mira Anindya",
        profile_rangga: "Rangga Aditya",
        profile_farah: "Farah Novita",
        profile_bima: "Bima Satrio",
        profile_pakHendra: "Mr. Hendra",
        profile_buSari: "Mrs. Sari",
        profile_alvin: "Alvin Pradana",
        lockText: "🔒 Locked",
        lockRouteA: "🔒 Complete Alexandra's Route",
        lockRouteB: "🔒 Complete Kirana's Route",
        lockRouteM: "🔒 Complete Mira's Route",
        lockSecret: "🔒 Complete All Heroines' Routes",
    },
    id: {
        langName: "Indonesia",
        gameTitle: "Persimpangan Hati",
        gameSub: "Visual Novel Romansa Sekolah",
        btnContinue: "▶ LANJUTKAN",
        btnNewGame: "▶ MULAI BARU",
        btnProfiles: "📖 PROFIL KARAKTER",
        btnGallery: "📖 KOLEKSI QUOTES",
        btnSettings: "⚙️ PENGATURAN",
        inputTitle: "SIAPA NAMA KAMU?",
        inputSub: "Masukkan nama panggilan karakter utama",
        inputPlaceholder: "Contoh: Adi",
        inputBtnStart: "Mulai Masuk Cerita",
        inputBtnCancel: "Batal",
        pauseTitle: "⏸️ Jeda",
        pauseSave: "💾 Simpan",
        pauseLoad: "📂 Lanjutkan (Muat Slot)",
        pauseSettings: "⚙️ Pengaturan",
        pauseQuit: "🚪 Keluar Game",
        pauseBack: "Kembali",
        settingsTitle: "⚙️ Pengaturan",
        settingsBGM: "🎵 Musik Latar (BGM)",
        settingsSFX: "🔊 Efek Suara (SFX)",
        settingsRes: "🖥️ Resolusi Layar",
        settingsLang: "🌐 Bahasa",
        settingsBack: "Kembali",
        saveLoadTitleSave: "💾 Simpan Permainan",
        saveLoadTitleLoad: "📂 Muat Permainan",
        saveLoadSubSave: "Pilih slot untuk menyimpan progress kamu",
        saveLoadSubLoad: "Pilih slot yang ingin dimuat",
        saveLoadBack: "Kembali",
        confirmYes: "Ya, Lanjutkan",
        confirmNo: "Batal",
        confirmQuitTitle: "🚪 Keluar?",
        confirmQuitMsg: "Yakin ingin keluar game? Progress yang belum disimpan akan hilang.",
        confirmOverwriteTitle: "Timpa Slot?",
        confirmOverwriteMsg: "Slot {n} sudah terisi ({date}). Timpa dengan progress saat ini?",
        confirmLoadTitle: "Muat Slot Ini?",
        confirmLoadMsg: "Progress yang belum disimpan saat ini akan hilang. Lanjutkan memuat Slot {n}?",
        confirmDeleteTitle: "Hapus Slot?",
        confirmDeleteMsg: "Slot {n} akan dihapus permanen dan tidak bisa dikembalikan.",
        toastUnlock: "Sesuatu Terbuka!",
        toastUnlockMsg: "Cek menu untuk melihatnya.",
        toastSave: "✅ Tersimpan!",
        toastSaveMsg: "Progress berhasil disimpan di Slot {n}.",
        profile_mc: "MC (Adi Pratama)",
        profile_alexandra: "Alexandra Wijaya",
        profile_kirana: "Kirana Maheswari",
        profile_mira: "Mira Anindya",
        profile_rangga: "Rangga Aditya",
        profile_farah: "Farah Novita",
        profile_bima: "Bima Satrio",
        profile_pakHendra: "Pak Hendra",
        profile_buSari: "Bu Sari",
        profile_alvin: "Alvin Pradana",
        lockText: "🔒 Terkunci",
        lockRouteA: "🔒 Selesaikan Rute Alexandra",
        lockRouteB: "🔒 Selesaikan Rute Kirana",
        lockRouteM: "🔒 Selesaikan Rute Mira",
        lockSecret: "🔒 Selesaikan Semua Rute Heroine",
    }
};

const characterProfiles = {
    mc: { id: 'mc', name: 'MC (Adi Pratama)', role: 'Protagonis', desc: 'Murid kelas 2 SMA biasa. Nilai pas-pasan, hobi baca komik dan tidur di kelas. Baik hati, agak canggung, tapi selalu berusaha jujur pada dirinya sendiri.', unlockKey: null },
    alexandra: { id: 'alexandra', name: 'Alexandra Wijaya', role: 'Ketua OSIS', desc: 'Tegas, disiplin, perfeksionis. Di balik topeng ketegasannya, dia menyimpan kecemasan dan kesepian. Takut mengecewakan orang lain dan jarang membiarkan siapa pun dekat.', unlockKey: 'routeA' },
    kirana: { id: 'kirana', name: 'Kirana Maheswari', role: 'Jenius Seni Sekolah', desc: 'Ceria, kreatif, dan bebas. Juara lomba lukis nasional. Namun diam-diam ia takut jika suatu hari bakatnya hilang, orang-orang akan berhenti menyukainya.', unlockKey: 'routeB' },
    mira: { id: 'mira', name: 'Mira Anindya', role: 'Murid Pindahan', desc: 'Pendiam, waspada, dan sangat cerdas. Sudah pindah sekolah empat kali dalam tiga tahun. Suka menulis cerpen di loteng arsip perpustakaan, dan belajar untuk tidak terlalu dekat dengan siapa pun agar tidak sakit hati saat harus pergi lagi.', unlockKey: 'routeM' },
    rangga: { id: 'rangga', name: 'Rangga Aditya', role: 'Wakil Ketua OSIS', desc: 'Bertanggung jawab dan protektif, terutama pada Alexandra. Awalnya sangat curiga pada MC, tapi akhirnya memberikan restunya. Diam-diam menyukai Alexandra.', unlockKey: 'secretRoute' },
    farah: { id: 'farah', name: 'Farah Novita', role: 'Sekretaris OSIS', desc: 'Ramah dan empatik. Sahabat Alexandra sejak SMP, sering menjadi "penerjemah" perasaan Alexandra yang sulit diungkapkan. Selalu membawa buku catatan kecil.', unlockKey: 'secretRoute' },
    bima: { id: 'bima', name: 'Bima Satrio', role: 'Sahabat MC', desc: 'Humoris, cerewet, dan sumber gosip sekolah. Meski kadang nyebelin, dia adalah sahabat paling setia yang selalu siap jadi tempat curhat MC.', unlockKey: null },
    pakHendra: { id: 'pakHendra', name: 'Pak Hendra', role: 'Wali Kelas (Guru Matematika)', desc: 'Tegas soal akademik, tetapi sangat perhatian. Pengalaman mengajar 28 tahun membuatnya tidak mudah dibohongi, dan nasihatnya selalu bijak.', unlockKey: null },
    buSari: { id: 'buSari', name: 'Bu Sari', role: 'Guru Seni', desc: 'Tenang dan sabar. Mentor Kirana. Dia sengaja "meminjam" MC untuk membantu Kirana agar mereka berdua bisa saling mengenal lebih dalam.', unlockKey: 'secretRoute' },
    alvin: { id: 'alvin', name: 'Alvin Pradana', role: 'Sahabat Masa Kecil', desc: 'Sahabat Mira sejak SD. Sudah lama menyukainya tapi takut mengungkapkan. Baik hati, tapi bisa menjadi rival yang serius.', unlockKey: null }
};